version: '3.8'

services:
  stock-service:
    container_name: ruoyi-stock
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GEMINI_API_URL=${GEMINI_API_URL}
      - NACOS_SERVER_ADDRESS=${NACOS_SERVER_ADDRESS}
      - DB_HOST_NAME=${DB_HOST_NAME}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - docker_ruoyi-network
networks:
  docker_ruoyi-network:
    external: true